AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  logIn:
    Type: 'AWS::Serverless::Function'
    Role: 'arn:aws:iam::754778745637:role/LambdaDynamoDBRole'
    Properties:
      Handler: logIn/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 1024
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /
            Method: ANY
  logInPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - logIn
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getUserId:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getUserId/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  followers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: followers/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  userNames:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: userNames/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  followings:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: followings/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  updateUsers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updateUsers/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 192
      Timeout: 15
  follow:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: follow/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  unfollow:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: unfollow/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  updateBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updateBot/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  readFollowers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: readFollowers/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  readFollowings:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: readFollowings/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  unfollowers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: unfollowers/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::754778745637:role/LambdaDynamoDBRole'
  startBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: startBot/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::754778745637:role/LambdaDynamoDBRole'
  searchFans:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: searchFans/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::754778745637:role/LambdaDynamoDBRole'
