AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  logIn:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: logIn/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 1024
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /
            Method: ANY
  logInPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - logIn
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getUserId:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getUserId/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  followers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: followers/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  userNames:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: userNames/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  followings:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: followings/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
  updateUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updateUser/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::754778745637:role/LambdaDynamoDBRole'
